export type BrandEntry = {
  slug: string;
  name: string;
  category: "watches" | "fragrance";
  blurb: string;
  founded: number;
  country: string;
  founderName: string;
  founderStory: string;
  warranty: string;
  priceRange: string;
  specialty: string;
  notableModels: string[];
};

export const watchBrands: BrandEntry[] = [
  {
    slug: "omega",
    name: "Omega",
    category: "watches",
    founded: 1848,
    country: "Switzerland",
    founderName: "Louis Brandt",
    specialty: "Professional & Dress Watches",
    priceRange: "$2,000 – $12,000+",
    warranty: "5 years",
    notableModels: ["Seamaster", "Speedmaster", "Constellation", "De Ville"],
    founderStory: "Louis Brandt founded Omega in La Chaux-de-Fonds in 1848 at just 23 years old, assembling pocket watches from parts sourced across Europe. By the time his sons took over, the brand had established a reputation for precision that would later earn it contracts with the US Army and the British Royal Flying Corps.",
    blurb: "Founded in 1848 and worn on the moon in 1969. Omega's Seamaster and Speedmaster lines are two of the most respected references in horology — built for professional use, collected for life. Their movements are certified by METAS to a standard stricter than COSC.",
  },
  {
    slug: "rolex",
    name: "Rolex",
    category: "watches",
    founded: 1905,
    country: "Switzerland",
    founderName: "Hans Wilsdorf",
    specialty: "Luxury Sports & Dress Watches",
    priceRange: "$6,000 – $50,000+",
    warranty: "5 years",
    notableModels: ["Submariner", "Daytona", "GMT-Master II", "Datejust", "Explorer"],
    founderStory: "Hans Wilsdorf co-founded Rolex in London in 1905 with a single ambition: put a reliable, accurate watch on the wrist. He pioneered the wristwatch at a time when pocket watches dominated, and his obsession with waterproofing led to the Oyster case in 1926 — the world's first waterproof wristwatch.",
    blurb: "The benchmark since 1905. The Submariner, Daytona, GMT-Master, and Datejust are not just watches — they are proven stores of value that hold and appreciate over decades. Rolex controls every step of production in-house, which is why the standard never slips.",
  },
  {
    slug: "longines",
    name: "Longines",
    category: "watches",
    founded: 1832,
    country: "Switzerland",
    founderName: "Auguste Agassiz",
    specialty: "Elegance & Heritage Watches",
    priceRange: "$700 – $3,500",
    warranty: "2 years",
    notableModels: ["Master Collection", "Conquest", "HydroConquest", "Spirit"],
    founderStory: "Auguste Agassiz founded Longines in Saint-Imier in 1832. The brand became the first Swiss watchmaker to register a trademark — a winged hourglass still used today. Their timekeeping precision earned them roles as the official timekeeper at the Olympics, FIFA World Cup, and countless other international events.",
    blurb: "Swiss precision since 1832. Longines makes a clear argument that elegance does not require extravagance. Their Heritage and Conquest collections offer genuine Swiss craftsmanship at price points that respect the buyer. One of the most decorated names in the industry.",
  },
  {
    slug: "tudor",
    name: "Tudor",
    category: "watches",
    founded: 1926,
    country: "Switzerland",
    founderName: "Hans Wilsdorf",
    specialty: "Sport & Adventure Watches",
    priceRange: "$1,500 – $5,000",
    warranty: "5 years",
    notableModels: ["Black Bay", "Black Bay Pro", "Pelagos", "Ranger"],
    founderStory: "Hans Wilsdorf — the same founder as Rolex — created Tudor in 1926 to offer a more accessible alternative with the same quality DNA. For decades Tudor was Rolex's quiet sibling. When they reintroduced the Black Bay in 2012 with an in-house movement, collectors stopped treating them as second-best.",
    blurb: "Rolex's sibling brand, built for buyers who want the DNA without the waitlist. Tudor's Black Bay collection has earned its following on merit — not just because of the family connection. In-house movements, serious build quality, serious value.",
  },
  {
    slug: "frederique-constant",
    name: "Frederique Constant",
    category: "watches",
    founded: 1988,
    country: "Switzerland",
    founderName: "Peter and Aletta Stas",
    specialty: "Accessible Complications",
    priceRange: "$700 – $4,000",
    warranty: "2 years",
    notableModels: ["Classics", "Highlife", "Slimline Moonphase", "Perpetual Calendar"],
    founderStory: "Peter and Aletta Stas founded Frederique Constant in Geneva in 1988 with a mission to offer Swiss luxury watches at accessible price points. In 2004, they became only the third brand in Geneva to develop and manufacture their own movement in the modern era — a feat that earned them the respect of the broader watchmaking community.",
    blurb: "Geneva-based and independently minded. Frederique Constant produces in-house movements at accessible price points, making them a consistent choice among collectors who understand what's inside the case. Dress watches and complications done right.",
  },
  {
    slug: "tag-heuer",
    name: "TAG Heuer",
    category: "watches",
    founded: 1860,
    country: "Switzerland",
    founderName: "Edouard Heuer",
    specialty: "Sports Chronographs",
    priceRange: "$1,500 – $8,000+",
    warranty: "2 years",
    notableModels: ["Carrera", "Monaco", "Aquaracer", "Formula 1"],
    founderStory: "Edouard Heuer founded his workshop in Saint-Imier in 1860 at the age of 20. His obsession with measuring time precisely led to innovations in stopwatch technology that made his brand the official timekeeper for the 1920 and 1924 Olympics. The Monaco — made famous by Steve McQueen in Le Mans — cemented TAG Heuer's place in racing and film history permanently.",
    blurb: "The watch of racing and cinema. TAG Heuer's Carrera and Monaco are two of the most recognizable chronographs in the world. Built for performance, worn for character. Their Swiss movements and sport-forward design make them standout pieces at every price point in their range.",
  },
  {
    slug: "tissot",
    name: "Tissot",
    category: "watches",
    founded: 1853,
    country: "Switzerland",
    founderName: "Charles-Félicien Tissot",
    specialty: "Value Swiss Watchmaking",
    priceRange: "$300 – $1,500",
    warranty: "2 years",
    notableModels: ["PRX", "Le Locle", "Seastar", "T-Touch", "Chemin des Tourelles"],
    founderStory: "Charles-Félicien Tissot and his son Charles-Émile founded their company in Le Locle in 1853. They were the first watch company to produce a pocket watch with two time zones — in 1853, before world travel was common. Their instinct for innovation at an accessible price has never left them.",
    blurb: "The gateway into Swiss watchmaking, and for many collectors, the brand they come back to. Tissot delivers genuine Swiss movements, solid build quality, and clean design at prices that don't require justification. The PRX alone is one of the best-designed watches at any price point right now.",
  },
  {
    slug: "seiko",
    name: "Seiko",
    category: "watches",
    founded: 1881,
    country: "Japan",
    founderName: "Kintaro Hattori",
    specialty: "Japanese Precision",
    priceRange: "$150 – $6,000+",
    warranty: "3 years",
    notableModels: ["Prospex", "Presage", "5 Sports", "Alpinist", "Grand Seiko Snowflake"],
    founderStory: "Kintaro Hattori opened a clock and watch shop in Tokyo in 1881 at the age of 21. He began manufacturing under the Seiko name in 1924. Seiko went on to shock the Swiss industry in 1969 with the Astron — the world's first quartz watch — and has never stopped pushing the boundaries of what a watch can be at every price point.",
    blurb: "Few brands have done more for watchmaking at every price point. Seiko's entry-level pieces outperform the competition by every objective measure. Their Grand Seiko division competes directly with Swiss giants on dial finishing — and often wins.",
  },
  {
    slug: "movado",
    name: "Movado",
    category: "watches",
    founded: 1881,
    country: "Switzerland",
    founderName: "Achilles Ditesheim",
    specialty: "Design-Forward Minimalism",
    priceRange: "$400 – $2,500",
    warranty: "2 years",
    notableModels: ["Museum Classic", "Bold", "Heritage", "Sapphire"],
    founderStory: "Achilles Ditesheim founded Movado in La Chaux-de-Fonds in 1881. The company became famous not just for precision but for art — their timepieces won 100 timing contests and 95 international awards by 1900. The Museum dial, introduced in 1947, was created by American artist Nathan George Horwitt and permanently changed how the world thinks about watch design.",
    blurb: "Known for the Museum dial — a single dot at 12, nothing else. Movado makes a bold design statement at mid-range prices. Their pieces reward people who value minimalism over complication, and who understand that restraint is its own kind of confidence.",
  },
  {
    slug: "citizen",
    name: "Citizen",
    category: "watches",
    founded: 1918,
    country: "Japan",
    founderName: "Rodolphe Schmitt",
    specialty: "Eco-Drive Technology",
    priceRange: "$200 – $2,000",
    warranty: "5 years",
    notableModels: ["Promaster Navihawk", "Eco-Drive Chandler", "Satellite Wave", "The Citizen"],
    founderStory: "The Citizen Watch Company was established in Tokyo in 1918 and named 'Citizen' in 1924 with the aim of being a watch accessible to all citizens. Their breakthrough came in 1976 with the world's first light-powered analog quartz watch — technology that evolved into Eco-Drive, which can charge from any light source and never needs a battery.",
    blurb: "Citizen's Eco-Drive technology — solar-powered, never needs a battery — is one of the genuinely clever innovations in modern watchmaking. Reliable, precise, and well-built at their price point. Their Promaster and Satellite Wave lines have real followings among people who want function without compromise.",
  },
  {
    slug: "bulova",
    name: "Bulova",
    category: "watches",
    founded: 1875,
    country: "United States",
    founderName: "Joseph Bulova",
    specialty: "American Precision",
    priceRange: "$200 – $1,500",
    warranty: "3 years",
    notableModels: ["Precisionist", "Lunar Pilot", "Oceanographer", "Devil Diver"],
    founderStory: "Joseph Bulova emigrated from Bohemia to New York in 1875 and opened a small jewelry shop on Maiden Lane. He grew it into the first company to mass-produce watches with fully standardized parts. In 1960, a Bulova was the first watch worn in space by Wally Schirra. The Lunar Pilot — based on that exact watch — is still in production today.",
    blurb: "An American institution since 1875. Bulova's Precisionist line uses a proprietary three-pronged tuning fork movement to achieve accuracy that rivals movements costing far more. A brand with serious heritage that is currently undervalued by the broader market.",
  },
  {
    slug: "invicta",
    name: "Invicta",
    category: "watches",
    founded: 1837,
    country: "Switzerland",
    founderName: "Rafael Picard",
    specialty: "Bold Entry-Level Watches",
    priceRange: "$50 – $500",
    warranty: "1 year",
    notableModels: ["Pro Diver", "Subaqua", "Reserve", "Bolt"],
    founderStory: "Rafael Picard founded Invicta in La Chaux-de-Fonds in 1837. The brand nearly disappeared in the 1970s quartz crisis, was revived in the 1990s, and rebuilt its identity around bold design at accessible prices. Their Pro Diver has become one of the best-selling watch references in the world — proof that value and character can coexist.",
    blurb: "Bold, oversized, and unapologetically confident. Invicta built its following on delivering big watch energy at entry-level prices. The Pro Diver has become a cult reference — a genuine starting point for collectors who are just beginning to explore the space.",
  },
];

export const fragranceBrands: BrandEntry[] = [
  {
    slug: "tom-ford",
    name: "Tom Ford",
    category: "fragrance",
    founded: 2006,
    country: "United States",
    founderName: "Tom Ford",
    specialty: "Luxury & Private Blend Fragrances",
    priceRange: "$150 – $500+",
    warranty: "N/A",
    notableModels: ["Noir de Noir", "Tobacco Vanille", "Oud Wood", "Black Orchid", "Lost Cherry"],
    founderStory: "Tom Ford launched his eponymous fragrance line in 2006 after leaving Gucci, where he had transformed the brand's identity. His Private Blend collection — positioned as a luxury atelier line — brought niche perfumery sensibility to a globally distributed brand. Each scent is treated as an art object with a point of view.",
    blurb: "Tom Ford's fragrance line is uncompromising. Private Blend and the main collection push concentration and complexity to places mass-market houses do not go. Noir de Noir, Tobacco Vanille, and Oud Wood have become modern classics.",
  },
  {
    slug: "creed",
    name: "Creed",
    category: "fragrance",
    founded: 1760,
    country: "France",
    founderName: "James Henry Creed",
    specialty: "Heritage Luxury Fragrance",
    priceRange: "$300 – $600+",
    warranty: "N/A",
    notableModels: ["Aventus", "Green Irish Tweed", "Silver Mountain Water", "Viking"],
    founderStory: "James Henry Creed established the house in London in 1760, initially as a tailor and glover to the English aristocracy. Fragrance became the focus when the house relocated to Paris. Their clients have included Napoleon III, Queen Victoria, and Prince Charles — a lineage that gives Aventus, launched in 2010, something to live up to. It does.",
    blurb: "Founded in 1760, Creed is one of the oldest fragrance houses in the world. Aventus became a cultural touchstone for a reason — projection, longevity, and a complexity that rewards the nose. Their silver-top bottles are instantly recognizable to anyone who knows fragrance.",
  },
  {
    slug: "dior",
    name: "Dior",
    category: "fragrance",
    founded: 1947,
    country: "France",
    founderName: "Christian Dior",
    specialty: "French Heritage Perfumery",
    priceRange: "$100 – $400+",
    warranty: "N/A",
    notableModels: ["Sauvage", "Miss Dior", "J'adore", "Fahrenheit", "La Collection Privée"],
    founderStory: "Christian Dior launched his fashion house in 1946 and his first fragrance — Miss Dior — in 1947, the same year as his debut collection. He believed a fragrance was the finishing touch to a look. Sauvage, launched in 2015 and reformulated by perfumer François Demachy, became one of the best-selling men's fragrances in history almost immediately.",
    blurb: "Christian Dior's fragrance portfolio spans decades and price points without losing its identity. Sauvage is one of the best-selling men's fragrances globally for good reason. The La Collection Privée line goes deeper for those who want something more singular.",
  },
  {
    slug: "versace",
    name: "Versace",
    category: "fragrance",
    founded: 1978,
    country: "Italy",
    founderName: "Gianni Versace",
    specialty: "Bold Italian Luxury",
    priceRange: "$60 – $150",
    warranty: "N/A",
    notableModels: ["Eros", "Dylan Blue", "Pour Homme", "Bright Crystal", "Yellow Diamond"],
    founderStory: "Gianni Versace founded his fashion house in Milan in 1978. His fragrances carry the same unapologetic confidence as his clothing — bold, recognizable, and designed to be noticed. Eros, launched in 2012 and named for the Greek god of love, became a defining fragrance of its decade.",
    blurb: "Versace fragrance is confident by design — bold projection, clear identity, and a price point that makes them genuinely accessible. Eros and Pour Homme have proven staying power over years in the market. The kind of fragrances that generate compliments.",
  },
  {
    slug: "byredo",
    name: "Byredo",
    category: "fragrance",
    founded: 2006,
    country: "Sweden",
    founderName: "Ben Gorham",
    specialty: "Niche & Conceptual Fragrance",
    priceRange: "$200 – $450",
    warranty: "N/A",
    notableModels: ["Gypsy Water", "Bal d'Afrique", "Mojave Ghost", "Bibliothèque", "Blanche"],
    founderStory: "Ben Gorham — a former professional basketball player — founded Byredo in Stockholm in 2006 with no formal training in perfumery. He worked with master perfumer Jérôme Epinette and approached each fragrance as a narrative object. Byredo's refusal to advertise and its limited distribution created scarcity that word of mouth turned into cult status.",
    blurb: "Swedish-born and deliberately quiet. Byredo does not advertise. Their fragrances — Gypsy Water, Bal d'Afrique, Mojave Ghost — build followings through merit alone. For buyers who know the niche world and want something that won't be on everyone else.",
  },
  {
    slug: "cartier",
    name: "Cartier",
    category: "fragrance",
    founded: 1847,
    country: "France",
    founderName: "Louis-François Cartier",
    specialty: "Refined French Luxury",
    priceRange: "$100 – $350",
    warranty: "N/A",
    notableModels: ["Déclaration", "Santos", "Pasha", "Les Heures", "La Panthère"],
    founderStory: "Louis-François Cartier took over his master's jewelry workshop in Paris in 1847. His grandsons Louis, Pierre, and Jacques turned it into a global luxury empire. When Cartier entered fragrance in 1981 with Must de Cartier, they brought the same precision and restraint that defined their jewelry — an approach that has never wavered.",
    blurb: "The house of Cartier brings the same precision to fragrance that defines their jewelry and watches. Déclaration and Les Heures remain among the most refined offerings in men's and unisex perfumery. Understated in the best sense — quality that doesn't need to announce itself.",
  },
  {
    slug: "giorgio-armani",
    name: "Giorgio Armani",
    category: "fragrance",
    founded: 1975,
    country: "Italy",
    founderName: "Giorgio Armani",
    specialty: "Italian Elegance",
    priceRange: "$80 – $200",
    warranty: "N/A",
    notableModels: ["Acqua di Giò", "Acqua di Giò Profumo", "Sì", "Code", "Emporio Armani Stronger With You"],
    founderStory: "Giorgio Armani opened his fashion house in Milan in 1975. His aesthetic — understated luxury, clean lines, neutral tones — translated directly into fragrance. Acqua di Giò, launched in 1996 and inspired by the Mediterranean island of Pantelleria, became one of the most influential men's fragrances ever created and remains a consistent global bestseller nearly 30 years later.",
    blurb: "Armani fragrances anchor the accessible-luxury tier without compromise. Acqua di Giò has been among the best-selling men's fragrances for over 25 years — a record built on genuine quality. Si and Acqua di Giò Profumo hold the same standard.",
  },
  {
    slug: "paco-rabanne",
    name: "Paco Rabanne",
    category: "fragrance",
    founded: 1966,
    country: "Spain",
    founderName: "Francisco Rabaneda Cuervo",
    specialty: "Bold & Statement Fragrance",
    priceRange: "$70 – $160",
    warranty: "N/A",
    notableModels: ["1 Million", "Invictus", "Lady Million", "Olympéa"],
    founderStory: "Francisco Rabaneda Cuervo — known as Paco Rabanne — launched his fashion house in Paris in 1966, famously building dresses from metal and plastic rather than fabric. His fragrance line carries that same audacity. 1 Million, launched in 2008 in a gold-bar bottle, and Invictus, launched in 2013, redefined what bold men's fragrance could look and smell like.",
    blurb: "1 Million and Invictus created a new template for bold, confident men's fragrance. Paco Rabanne's willingness to push into territory other houses avoid has made them enduring catalog staples that generate immediate reactions — which is the point.",
  },
  {
    slug: "burberry",
    name: "Burberry",
    category: "fragrance",
    founded: 1856,
    country: "United Kingdom",
    founderName: "Thomas Burberry",
    specialty: "British Heritage Fragrance",
    priceRange: "$80 – $180",
    warranty: "N/A",
    notableModels: ["Her", "Brit", "Weekend", "Touch", "Mr. Burberry"],
    founderStory: "Thomas Burberry opened his outfitter's shop in Basingstoke in 1856 at age 21. He invented gabardine fabric in 1879 — a breathable, weatherproof material that became the foundation of the trench coat. Burberry's fragrance line translates that heritage into scent: structured, weather-resistant in its own way, and very British in its restraint.",
    blurb: "Burberry translates its heritage aesthetic into fragrance with consistency. Her, Weekend, and Brit occupy the refined British middle ground — approachable without being ordinary. Well-constructed, well-priced, and recognizable for the right reasons.",
  },
  {
    slug: "calvin-klein",
    name: "Calvin Klein",
    category: "fragrance",
    founded: 1968,
    country: "United States",
    founderName: "Calvin Klein",
    specialty: "American Minimalism",
    priceRange: "$40 – $120",
    warranty: "N/A",
    notableModels: ["CK One", "Obsession", "Eternity", "Euphoria", "CKBE"],
    founderStory: "Calvin Klein launched his fashion label in New York in 1968. His first fragrance, Obsession, arrived in 1985 with one of the most provocative advertising campaigns in history. But it was CK One in 1994 — the first major unisex fragrance — that changed the industry. It proved that gender-neutral perfumery could be commercially enormous, not just a niche experiment.",
    blurb: "CK One changed the fragrance industry in 1994 by making unisex mainstream. The line has held that clean, minimalist identity ever since. Eternity and Obsession remain among the most recognizable fragrances in the world. Entry-level luxury with a real point of view.",
  },
  {
    slug: "azzaro",
    name: "Azzaro",
    category: "fragrance",
    founded: 1967,
    country: "France",
    founderName: "Loris Azzaro",
    specialty: "Fresh & Clean Masculine",
    priceRange: "$35 – $100",
    warranty: "N/A",
    notableModels: ["Chrome", "Wanted", "Most Wanted", "Chrome United"],
    founderStory: "Loris Azzaro moved from Tunisia to Paris and opened his couture house in 1967. His designs were flamboyant, glittering, made for nightlife. Chrome, launched in 1996 — clean, aquatic, understated — was the opposite of everything he designed. It became his most enduring product. Chrome has been among the most consistently worn men's fragrances for nearly 30 years.",
    blurb: "Chrome has been a benchmark of fresh, clean men's fragrance since 1996. Azzaro's lineup is consistent — accessible price points, dependable quality, and a signature character that has never tried too hard. Chrome United and Wanted fill out a lineup worth knowing.",
  },
  {
    slug: "coach",
    name: "Coach",
    category: "fragrance",
    founded: 1941,
    country: "United States",
    founderName: "Miles Cahn",
    specialty: "American Leather-Goods Heritage",
    priceRange: "$50 – $130",
    warranty: "N/A",
    notableModels: ["Dreams", "Wild Rose", "Floral", "Coach for Men", "Open Road"],
    founderStory: "Miles Cahn founded Coach in a Manhattan loft in 1941, initially producing leather goods by hand. The brand grew into one of America's most recognized luxury accessories companies. Their fragrance line, launched more recently, carries the same American-crafted-leather heritage — clean, unpretentious, and built to last.",
    blurb: "Coach brings its American leather-goods heritage into fragrance with a clean, polished aesthetic. Dreams and Wild Rose have built a loyal following among buyers who want quality without the European luxury premium. Well-made and distinctly American in character.",
  },
];

export function getBrand(slug: string, category: "watches" | "fragrance"): BrandEntry | undefined {
  const list = category === "watches" ? watchBrands : fragranceBrands;
  return list.find(b => b.slug === slug);
}

export function brandToSlug(name: string): string {
  return name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}

export const allWatchBrandSlugs    = watchBrands.map(b => ({ brand: b.slug }));
export const allFragranceBrandSlugs = fragranceBrands.map(b => ({ brand: b.slug }));
